CREATE DATABASE StudentDetails;
USE StudentDetails;
CREATE TABLE Details (
    Id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RollNumber CHAR(10) NOT NULL UNIQUE,
    StudentName VARCHAR(30) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    PhoneNo VARCHAR(15) NOT NULL
);